---
title: "Creating function load_estab"
author: "Daniel Grimaldi / Schar School of Public Policy"
date: "`r Sys.time()`"
output:
  html_document:
    theme: united
    number_sections: false
---

This script creates a lower-level function (load_estab) used by the upper-level function load_rais to load raw registries from RAIS Establishments (RAIS-Estab).

```{r setup, echo=FALSE, warning=FALSE, message=FALSE}
if(!require(data.table)){install.packages("data.table")}
```

```{r, echo=TRUE, warning=FALSE, message=FALSE}
load_estab <- function(year, main.source, n.registries){
  
  year.source <- paste0(main.source, "/", year, ".zip")
  temp.folder <- paste0(getwd(), "/temp")
  unzip(zipfile=year.source, exdir=temp.folder)
  temp.source <- paste(temp.folder, year, sep="/")
  using.folder <- paste0(temp.source, "/using")
  dir.create(using.folder)  

  if(year %in% c(2002:2006)){
    estab.file <- paste(temp.source,
                      grep("^Estb", list.files(temp.source), value = TRUE),
                      sep="/")
    unzip(zipfile=estab.file, exdir = using.folder)
    file.i <- list.files(using.folder, full.names=TRUE)
  }else{
    estab.file <- paste(temp.source,
                        grep("[E-e][S-s][T-t][B-b]", list.files(temp.source), value = TRUE),
                        sep="/")
    command.estab <- paste("7z x ", shQuote(estab.file), " -o", shQuote(using.folder), "", sep="")
    system(command.estab)
    file.i <- list.files(using.folder, full.names=TRUE)[1]
  }
  
  # loading into R
  data.estab <- fread(file=file.i, nrows=n.registries)
  # cleaning using folder (it always has only one file)
  unlink(file.i, recursive = FALSE)
  unlink(temp.folder, recursive = TRUE)
  data.estab
}
dump("load_estab", file="load_estab.R")
```